package com.android.billingclient.api;

import com.android.billingclient.api.BillingResult;

/* JADX INFO: compiled from: com.android.billingclient:billing@@3.0.3 */
/* JADX INFO: loaded from: classes.dex */
final class zzam {
    static final BillingResult zza;
    static final BillingResult zzb;
    static final BillingResult zzc;
    static final BillingResult zzd;
    static final BillingResult zze;
    static final BillingResult zzf;
    static final BillingResult zzg;
    static final BillingResult zzh;
    static final BillingResult zzi;
    static final BillingResult zzj;
    static final BillingResult zzk;
    static final BillingResult zzl;
    static final BillingResult zzm;
    static final BillingResult zzn;
    static final BillingResult zzo;
    static final BillingResult zzp;
    static final BillingResult zzq;
    static final BillingResult zzr;
    static final BillingResult zzs;
    static final BillingResult zzt;
    static final BillingResult zzu;
    static final BillingResult zzv;

    static {
        BillingResult.Builder builderNewBuilder = BillingResult.newBuilder();
        builderNewBuilder.setResponseCode(3);
        builderNewBuilder.setDebugMessage("Google Play In-app Billing API version is less than 3");
        zza = builderNewBuilder.build();
        BillingResult.Builder builderNewBuilder2 = BillingResult.newBuilder();
        builderNewBuilder2.setResponseCode(3);
        builderNewBuilder2.setDebugMessage("Google Play In-app Billing API version is less than 9");
        zzb = builderNewBuilder2.build();
        BillingResult.Builder builderNewBuilder3 = BillingResult.newBuilder();
        builderNewBuilder3.setResponseCode(3);
        builderNewBuilder3.setDebugMessage("Billing service unavailable on device.");
        zzc = builderNewBuilder3.build();
        BillingResult.Builder builderNewBuilder4 = BillingResult.newBuilder();
        builderNewBuilder4.setResponseCode(5);
        builderNewBuilder4.setDebugMessage("Client is already in the process of connecting to billing service.");
        zzd = builderNewBuilder4.build();
        BillingResult.Builder builderNewBuilder5 = BillingResult.newBuilder();
        builderNewBuilder5.setResponseCode(3);
        builderNewBuilder5.setDebugMessage("Play Store version installed does not support cross selling products.");
        zze = builderNewBuilder5.build();
        BillingResult.Builder builderNewBuilder6 = BillingResult.newBuilder();
        builderNewBuilder6.setResponseCode(5);
        builderNewBuilder6.setDebugMessage("The list of SKUs can't be empty.");
        zzf = builderNewBuilder6.build();
        BillingResult.Builder builderNewBuilder7 = BillingResult.newBuilder();
        builderNewBuilder7.setResponseCode(5);
        builderNewBuilder7.setDebugMessage("SKU type can't be empty.");
        zzg = builderNewBuilder7.build();
        BillingResult.Builder builderNewBuilder8 = BillingResult.newBuilder();
        builderNewBuilder8.setResponseCode(-2);
        builderNewBuilder8.setDebugMessage("Client does not support extra params.");
        zzh = builderNewBuilder8.build();
        BillingResult.Builder builderNewBuilder9 = BillingResult.newBuilder();
        builderNewBuilder9.setResponseCode(-2);
        builderNewBuilder9.setDebugMessage("Client does not support the feature.");
        zzi = builderNewBuilder9.build();
        BillingResult.Builder builderNewBuilder10 = BillingResult.newBuilder();
        builderNewBuilder10.setResponseCode(-2);
        builderNewBuilder10.setDebugMessage("Client does not support get purchase history.");
        zzj = builderNewBuilder10.build();
        BillingResult.Builder builderNewBuilder11 = BillingResult.newBuilder();
        builderNewBuilder11.setResponseCode(5);
        builderNewBuilder11.setDebugMessage("Invalid purchase token.");
        zzk = builderNewBuilder11.build();
        BillingResult.Builder builderNewBuilder12 = BillingResult.newBuilder();
        builderNewBuilder12.setResponseCode(6);
        builderNewBuilder12.setDebugMessage("An internal error occurred.");
        zzl = builderNewBuilder12.build();
        BillingResult.Builder builderNewBuilder13 = BillingResult.newBuilder();
        builderNewBuilder13.setResponseCode(4);
        builderNewBuilder13.setDebugMessage("Item is unavailable for purchase.");
        zzm = builderNewBuilder13.build();
        BillingResult.Builder builderNewBuilder14 = BillingResult.newBuilder();
        builderNewBuilder14.setResponseCode(5);
        builderNewBuilder14.setDebugMessage("SKU can't be null.");
        zzn = builderNewBuilder14.build();
        BillingResult.Builder builderNewBuilder15 = BillingResult.newBuilder();
        builderNewBuilder15.setResponseCode(5);
        builderNewBuilder15.setDebugMessage("SKU type can't be null.");
        zzo = builderNewBuilder15.build();
        BillingResult.Builder builderNewBuilder16 = BillingResult.newBuilder();
        builderNewBuilder16.setResponseCode(0);
        zzp = builderNewBuilder16.build();
        BillingResult.Builder builderNewBuilder17 = BillingResult.newBuilder();
        builderNewBuilder17.setResponseCode(-1);
        builderNewBuilder17.setDebugMessage("Service connection is disconnected.");
        zzq = builderNewBuilder17.build();
        BillingResult.Builder builderNewBuilder18 = BillingResult.newBuilder();
        builderNewBuilder18.setResponseCode(-3);
        builderNewBuilder18.setDebugMessage("Timeout communicating with service.");
        zzr = builderNewBuilder18.build();
        BillingResult.Builder builderNewBuilder19 = BillingResult.newBuilder();
        builderNewBuilder19.setResponseCode(-2);
        builderNewBuilder19.setDebugMessage("Client doesn't support subscriptions.");
        zzs = builderNewBuilder19.build();
        BillingResult.Builder builderNewBuilder20 = BillingResult.newBuilder();
        builderNewBuilder20.setResponseCode(-2);
        builderNewBuilder20.setDebugMessage("Client doesn't support subscriptions update.");
        zzt = builderNewBuilder20.build();
        BillingResult.Builder builderNewBuilder21 = BillingResult.newBuilder();
        builderNewBuilder21.setResponseCode(-2);
        builderNewBuilder21.setDebugMessage("Client doesn't support multi-item purchases.");
        zzu = builderNewBuilder21.build();
        BillingResult.Builder builderNewBuilder22 = BillingResult.newBuilder();
        builderNewBuilder22.setResponseCode(5);
        builderNewBuilder22.setDebugMessage("Unknown feature");
        zzv = builderNewBuilder22.build();
    }
}
